@startuml

title Write path with async=true and ES update fails

CQL -> Cassandra: insert into ...
Cassandra -> Table: insert()
Table -> EsSecondaryIndex: index()

EsSecondaryIndex -> ElasticIndex: index()
ElasticIndex -> ElasticSearch: client.prepareIndex().execute()
ElasticIndex -> EsSecondaryIndex: success
EsSecondaryIndex -> Table: success
Table -> Cassandra: SSTables modified
Cassandra -> CQL: inserted
ElasticSearch --> ElasticIndex: **<color red>failed - update lost</color>**

@enduml
