/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample;

import com.datastax.oss.driver.api.core.CqlSession;
import com.datastax.oss.driver.api.querybuilder.schema.CreateKeyspace;

import java.net.InetSocketAddress;

import static com.datastax.oss.driver.api.querybuilder.SchemaBuilder.createKeyspace;

public class App {


  public static void main(String[] args) {
    try {
      new App().connect();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  public synchronized Boolean connect() {
    System.out.println("connecting to cassandra");

    CqlSession session = CqlSession.builder()
      .addContactPoint(new InetSocketAddress("localhost", 9041))
      .withLocalDatacenter("datacenter1")
      .build();

    try {
      System.out.println("connected");
      CreateKeyspace createKs = createKeyspace("sample").withSimpleStrategy(1);
      session.execute(createKs.build());

      System.out.println("creating table");
      session.execute("CREATE TABLE sample.emails (\n"
        + "   id UUID PRIMARY KEY,\n"
        + "   subject text,\n"
        + "   body text,\n"
        + "   userid int,\n"
        + "   query text\n"
        + ");");

      System.out.println("done");
      System.out.println("creating index");
      session.execute("CREATE CUSTOM INDEX ON genesys.emails(query)\n"
        + "USING 'com.genesyslab.webme.commons.index.EsSecondaryIndex'\n"
        + "WITH OPTIONS = {'unicast-hosts': 'elasticsearchSample:9200'};");
      System.out.println("closing connection");
    } catch (Exception e) {
      session.close();
      return false;
    }
    System.out.println("done");

    return true;
  }
}
